
services:

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/linksaver
      JWT_SECRET: defa1925799c07918b1b18494bffeef6f048b31aa349c9a36d8ff3f537d89835

    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data: